// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPmDsOKfLRyfEzYW1LClHC6iKt2WpHvJY',
    appId: '1:990068334860:web:9c2c8783365e758862e929',
    messagingSenderId: '990068334860',
    projectId: 'ecoscan-ee6fe',
    authDomain: 'ecoscan-ee6fe.firebaseapp.com',
    storageBucket: 'ecoscan-ee6fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAli7Sj6kH0stsaA3hh85YMcET2rcD31KA',
    appId: '1:990068334860:android:3b23868cf8885b6862e929',
    messagingSenderId: '990068334860',
    projectId: 'ecoscan-ee6fe',
    storageBucket: 'ecoscan-ee6fe.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6PBushlEkk_T7jC75KDy7syXkq7cqgHU',
    appId: '1:990068334860:ios:1bfd082b7a89e42762e929',
    messagingSenderId: '990068334860',
    projectId: 'ecoscan-ee6fe',
    storageBucket: 'ecoscan-ee6fe.firebasestorage.app',
    iosBundleId: 'com.example.ecoscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPmDsOKfLRyfEzYW1LClHC6iKt2WpHvJY',
    appId: '1:990068334860:web:cae0f82054fe0f3562e929',
    messagingSenderId: '990068334860',
    projectId: 'ecoscan-ee6fe',
    authDomain: 'ecoscan-ee6fe.firebaseapp.com',
    storageBucket: 'ecoscan-ee6fe.firebasestorage.app',
  );
}
